Repository master-bard/master-bard, pull requests merged in 2023-07, with the labels that each got.

#3 feat: add prettier and readme technologies
  .prettierrc
  .vscode/settings.json
  README.md
Labels: documentation

#4 feat: added recommended extensions
  .vscode/extensions.json
Labels: enhancement

#7 feat: added prisma schema migration and seeder
  .env.sample
  .gitignore
  .prettierignore
  .vscode/extensions.json
  README.md
  libs/prisma/api/.eslintrc.json
  libs/prisma/api/README.md
  libs/prisma/api/jest.config.ts
  libs/prisma/api/project.json
  libs/prisma/api/src/index.ts
  libs/prisma/api/src/lib/prisma.module.ts
  libs/prisma/api/src/lib/prisma.service.spec.ts
  libs/prisma/api/src/lib/prisma.service.ts
  libs/prisma/api/tsconfig.json
  libs/prisma/api/tsconfig.lib.json
  libs/prisma/api/tsconfig.spec.json
  package-lock.json
  package.json
  prisma/migrations/20230708222944_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  tsconfig.base.json
Labels: setup, BE

#8 Feat/internationalize
  apps/api/tsconfig.json
  apps/ui-e2e/.eslintrc.json
  apps/ui-e2e/cypress.config.ts
  apps/ui-e2e/project.json
  apps/ui-e2e/src/e2e/app.cy.ts
  apps/ui-e2e/src/fixtures/example.json
  apps/ui-e2e/src/support/app.po.ts
  apps/ui-e2e/src/support/commands.ts
  apps/ui-e2e/src/support/e2e.ts
  apps/ui-e2e/tsconfig.json
  apps/ui/.babelrc
  apps/ui/.eslintrc.json
  apps/ui/.gitignore
  apps/ui/capacitor.config.ts
  apps/ui/ionic.config.json
  apps/ui/jest.config.ts
  apps/ui/package.json
  apps/ui/project.json
  apps/ui/src/App.test.tsx
  apps/ui/src/App.tsx
  apps/ui/src/assets/.gitkeep
  apps/ui/src/assets/icon/favicon.png
  apps/ui/src/assets/locales/en/example.json
  apps/ui/src/assets/locales/es/example.json
  apps/ui/src/assets/locales/fr/example.json
  apps/ui/src/components/ExploreContainer.css
  apps/ui/src/components/ExploreContainer.tsx
  apps/ui/src/environments/environment.prod.ts
  apps/ui/src/environments/environment.ts
  apps/ui/src/index.html
  apps/ui/src/main.tsx
  apps/ui/src/manifest.json
  apps/ui/src/pages/Tab1.css
  apps/ui/src/pages/Tab1.tsx
  apps/ui/src/pages/Tab2.css
  apps/ui/src/pages/Tab2.tsx
  apps/ui/src/pages/Tab3.css
  apps/ui/src/pages/Tab3.tsx
  apps/ui/src/setupTests.ts
  apps/ui/src/styles.css
  apps/ui/src/theme/variables.css
  apps/ui/tsconfig.app.json
  apps/ui/tsconfig.json
  apps/ui/tsconfig.spec.json
  apps/ui/webpack.config.js
  babel.config.json
  libs/translation/.eslintrc.json
  libs/translation/README.md
  libs/translation/jest.config.ts
  libs/translation/project.json
  libs/translation/src/index.ts
  libs/translation/src/lib/translation.ts
  libs/translation/tsconfig.json
  libs/translation/tsconfig.lib.json
  libs/translation/tsconfig.spec.json
  nx.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: setup, UI
